- Vagrantfile
- requirements.txt
Set up a VM for developing. I used flask-mongodbengine for Python3 to access MongoDB, let me know if you know a better/experienced package.
> add Vagrant files to set up VM

- service/models.py
I removed the unnecessary stackeholders field in promotion structure. Please review it!
> remove the stakeholders field

- .gitignore
- requirements.txt
- service/__init__.py
- service/models.py
- service/service.py
- Change a flask-mongo library to get rid of errors
- Remove some typos
- Remove unused imports
> Refine app skeleton

- .pylintrc
- requirements.txt
- service/__init__.py
- service/models.py
- service/service.py
- tests/__init__.py
- tests/promotion_factory.py
- tests/test_promotion.py
- tests/test_service.py
All tests pass
```
service/models.py        33      2    94%   37, 43
service/service.py       35      1    97%   40
TOTAL                    88      6    93%
```
Test coverage issue
- service/__init__.py: no idea how to test an exception throw in an `__init__.py` file
- service/models.py: line 37 and line 43 are inside Promotion field validation functions, I suppose that they will be tested when implementing the Create API
- service/service.py: line 40, this is the function for route('/'). It will be tested when implementing a complete function for the route('/')
pylint …
> Add list all promotions, query by promotion code feature

- service/models.py
- service/service.py
- tests/promotion_factory.py
- tests/test_promotion.py
- tests/test_service.py
```
Name                  Stmts   Miss  Cover
-----------------------------------------
service/__init__.py      20      3    85%
service/models.py        40      2    95%
service/service.py       42      1    98%
-----------------------------------------
TOTAL                   102      6    94%
----------------------------------------------------------------------
```
service/model.py 10.00/10
service/service.py 0.00/10
service/__init__.py -4.74/10
tests/ 6.07/10
> Read a promotion

- service/service.py
- tests/test_service.py
```
Name                  Stmts   Miss  Cover
-----------------------------------------
service/__init__.py      20      3    85%
service/models.py        40      2    95%
service/service.py       48      0   100%
-----------------------------------------
TOTAL                   108      5    95%
----------------------------------------------------------------------
```
service/model.py 10.00/10
service/service.py 0.21/10
tests/ 6.19/10
> list all apis

- service/models.py
- service/service.py
- tests/promotion_factory.py
- tests/test_promotion.py
- tests/test_service.py
Here, I change the API parameters from taking a list of product IDs to a list of product objects(in JSON format) and supposed that every product will have at least a `product_id` field and `price` field.
This API will return the given list of product objects with their updated prices.
```
service/models.py        44      2    95%   41, 47
service/service.py       86      1    99%   41
TOTAL                   150      6    96%
```
service/model.py: 9.77/10
service/service.py: 2.56/10
tests: 6.12/10
> Apply promotion on products

- service/service.py
- tests/test_service.py
```
service/models.py        44      2    95%   41, 47
service/service.py      112      0   100%
TOTAL                   176      5    97%
```
service/model.py: 9.77/10
service/service.py: 1.79/10
tests: 6.12/10
> add error handlers

- service/models.py
- service/service.py
- tests/test_promotion.py
- tests/test_service.py
- Get request body in `services.py`
- Add promotion through deserialization and serialization
- Add bad data format handler
- Add database validation error handler
> Add promotion

- service/models.py
- service/service.py
- tests/promotion_factory.py
- tests/test_promotion.py
- tests/test_service.py
All test cases fixed, coverage rate now is **98%**! Full coverage for `model.py` and `service.py`
```
service/models.py        58      0   100%
service/service.py      122      0   100%
TOTAL                   200      3    98%
```
> convert start_date and expiry_date to datetime objects

- service/models.py
- service/service.py
- tests/promotion_factory.py
- tests/test_promotion.py
- tests/test_service.py
```
service/models.py        55      0   100%
service/service.py      122      0   100%
TOTAL                   197      3    98%
```
Change the `Product` field in `Promotion` to be `ListField(Stringfield())` and modify corresponding code and tests
> Fix product field in Promotion

- .pylintrc
- service/models.py
- service/service.py
- tests/promotion_factory.py
- tests/test_promotion.py
- tests/test_service.py
```
service/models.py        52      0   100%
service/service.py      132      0   100%
TOTAL                   204      3    99%
```
- pylint tests/*: 9.92/10
- pylint service/*: 9.90/10
> Refine coding style

- .travis.yml
- README.md
- using Travis CI
- add Test badge
> Add Continuous Integration

- .travis.yml
- README.md
- requirements.txt
- Run code coverage after tests
- Add code coverage badge
> add codecov

- .pylintrc
- .travis.yml
- Vagrantfile
- requirements.txt
- service/__init__.py
- service/models.py
- service/service.py
- tests/promotion_factory.py
- tests/test_promotion.py
- tests/test_service.py
- update model
- update service
- update test cases
- update Travis
- update Promotion `start_date` and `expiry_date` field to be a timestamp
`pylint service/*`: 10/10
`pylint tests/*`: 10/10
> change DB from mongoDB to CouchDB

- Procfile
- requirements.txt
- Add honcho in `requirements.txt`
- Add Procfile
> Add honcho

- service/models.py
- service/static/index.html
- service/static/js/rest_api.js
- tests/test_promotion.py
- support create API in UI
- support update API in UI
- add time field, in format MM/DD/YYYY
- fix two test cases to as we changed to use the timestamp
> Enhance UI to support create and update APIs

- .travis.yml
- Vagrantfile
- requirements.txt
The Travis build failed because I didn't create feature files. 
```
$ behave
ConfigError: No steps directory in '/home/travis/build/devops-fall-2019-promotions-squad/promotions/features'
The command "behave" exited with 1.
```
I left feature files for #64. So the branch is ready for PR.
> support for BDD test

- .travis.yml
- features/environment.py
- features/promotions.feature
- features/steps/promotion_steps.py
- requirements.txt
- service/models.py
- service/service.py
- service/static/index.html
- tests/test_service.py
Create feature and steps files.
> Create feature and steps files

- features/promotions.feature
- features/steps/promotion_steps.py
Create scenario for update a promotion
> Scenario for update a promotion

- features/promotions.feature
- features/steps/promotion_steps.py
- service/static/index.html
- service/static/js/rest_api.js
- solved timestamp and date string conversion issue
> add apply-promotion BDD test

- manifest.yml
Setup the pipeline. This branch passed in 4 stages. 
Please also review the pipeline. 
After merging this branch to the master, I will change the pipeline input to the master branch.
> Devops pipeline

- features/promotions.feature
Create scenario for deleting a promotion
> adding scenario for deleting a promotion

- features/promotions.feature
fix a merge error when I merge the scenario for deletion branch
> fixing merge error

- features/promotions.feature
Create scenario for listing all promotions
> adding scenario for listing promotions

- requirements.txt
- service/service.py
- Refactor `Lisll All Promotions` API
- Put get Home page API before Swagger Docs.
- Otherwise, it doesn't work and gives you 404 Not Found
- I guess its because the Flask RestPlus take over the control of parsing the route '/'
> Refactor List-All-Promotions API

- service/service.py
Create `PromotionResource` Class
Add a route for delete
Rearrange the code
> Refactor delete

- service/service.py
* refactored `read a promotion`.
* removed 404 error handler. After I refactored the code, it didn't call this error handler any more.
* changed to api.url_for in `add a new promotion`
* changed the 404 error message in `read a promotion` to pass the step of `Then I should see the message "404 Not Found" ` in build. I will change the message back after the BDD file is changed.
> Refactor read

- service/service.py
- tests/test_service.py
- refactor update promotion API
- remove unnecessary `print` in unit tests
> Refactor update

- service/models.py
- service/service.py
- tests/test_promotion.py
- Add `DatabaseConnectionError` handler
- Refactor some import statements
> Refactor error handlers

- features/promotions.feature
- features/steps/promotion_steps.py
- requirements.txt
- service/models.py
- service/service.py
- tests/promotion_factory.py
- tests/test_promotion.py
- tests/test_service.py
We have finished the refactor part, so we should merge this `refactor` branch into `master` branch and merge new features into `master` branch instead of `refactor` branch afterwards
> Merge `refactor` branch into `master` branch

- service/static/index.html
- service/static/js/rest_api.js
> add a link to swagger docs on UI
